services:
  app:
    build: .
    container_name: multilevel-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./bot.db:/app/bot.db
    ports:
      - "8000:8000"
    networks:
      - multilevel_web

networks:
  multilevel_web:
    external: true
